######################################################################
# Automatically generated by qmake (2.01a) ? 5? 11 19:05:32 2014
######################################################################

TEMPLATE = app
TARGET = SpcObjRecog
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += spcobjrecog.h surf.h
FORMS += spcobjrecog.ui
SOURCES += main.cpp spcobjrecog.cpp surf.cpp
OBJECTS_DIR = ../obj/
DESTDIR = ../bin/
